import Backlight from "@/components/Backlight";
import Form from "@/components/Form";
import Main from "@/components/Main";

export default function ChatGPT() {
    return (
        <>
        <Backlight count={3} gap={100} />
        <Main>
            <Form
            type="topup"
            cover="steam_cover.png"
            boxes={[]}
            uniqueCard={{ title: "Steam", text: ["", `
            Подарочная карта Steam — это самый простой, быстрый и надежный способ пополнить счет. Вам не нужно передавать данные от аккаунта, достаточно указать свой E-mail для мгновенного получения кода активации. Вам остается лишь скопировать его и ввести.
            `],
            image: "steam_card.png"
            }}
            instructions={[[], [
                "Введите E-mail.",
                "Выберите регион.",
                "Выберите желаемый товар.",
                "Выберите способ оплаты.",
                "Примите условия  оферты.",
                "Оплатить товар."
            ]]}
            products={[
                { id: 722, name: "Steam Wallet Code - 10 USD (Argentina)", price: 1070, region: "Аргентина", image: "steam_back.png" },
                { id: 723, name: "Steam Wallet Code - 20 USD (Argentina)", price: 2130, region: "Аргентина", image: "steam_back.png" },
                { id: 724, name: "Steam Wallet Code - 50 USD (Argentina)", price: 5465, region: "Аргентина", image: "steam_back.png" },
                { id: 725, name: "Steam Wallet Code - 75 USD (Argentina)", price: 7285, region: "Аргентина" },
                { id: 726, name: "Steam Wallet Code - 100 USD (Argentina)", price: 9650, region: "Аргентина" },
                { id: 410, name: "Steam Wallet Code Brazil 10 BRL", price: 215, region: "Бразилия" },
                { id: 411, name: "Steam Wallet Code Brazil 20 BRL", price: 420, region: "Бразилия" },
                { id: 412, name: "Steam Wallet Code Brazil 30 BRL", price: 635, region: "Бразилия" },
                { id: 413, name: "Steam Wallet Code Brazil 50 BRL", price: 1055, region: "Бразилия" },
                { id: 415, name: "Steam Wallet Code Brazil 100 BRL", price: 2085, region: "Бразилия" },
                { id: 416, name: "Steam Wallet Code Brazil 150 BRL", price: 3175, region: "Бразилия" },
                { id: 417, name: "Steam Wallet Code Brazil 200 BRL", price: 4165, region: "Бразилия" },
                { id: 387, name: "Steam Wallet Code 5 GBP", price: 720, region: "Великобритания" },
                { id: 391, name: "Steam Wallet Code 10 GBP", price: 1440, region: "Великобритания" },
                { id: 393, name: "Steam Wallet Code 20 GBP", price: 2875, region: "Великобритания" },
                { id: 395, name: "Steam Wallet Code 25 GBP", price: 3780, region: "Великобритания" },
                { id: 319, name: "Steam Wallet 75.000 VND - (Vietnam)", price: 310, region: "Вьетнам" },
                { id: 318, name: "Steam Wallet 100.000 VND - (Vietnam)", price: 440, region: "Вьетнам" },
                { id: 321, name: "Steam Wallet 120.000 VND - (Vietnam)", price: 500, region: "Вьетнам" },
                { id: 322, name: "Steam Wallet 150.000 VND - (Vietnam)", price: 655, region: "Вьетнам" },
                { id: 320, name: "Steam Wallet 200.000 VND - (Vietnam)", price: 875, region: "Вьетнам" },
                { id: 323, name: "Steam Wallet 500.000 VND - (Vietnam)", price: 2170, region: "Вьетнам" },
                { id: 385, name: "Steam - Hong Kong HKD 1000", price: 0, region: "Гонконг" },
                { id: 325, name: "Steam Wallet Card 40 HKD", price: 510, region: "Гонконг" },
                { id: 365, name: "Steam Wallet Card 50 HKD", price: 640, region: "Гонконг" },
                { id: 366, name: "Steam Wallet Card 80 HKD", price: 1020, region: "Гонконг" },
                { id: 367, name: "Steam Wallet Card 100 HKD", price: 1275, region: "Гонконг" },
                { id: 368, name: "Steam Wallet Card 120 HKD", price: 1530, region: "Гонконг" },
                { id: 369, name: "Steam Wallet Card 150 HKD", price: 1910, region: "Гонконг" },
                { id: 370, name: "Steam Wallet Card 160 HKD", price: 2040, region: "Гонконг" },
                { id: 371, name: "Steam Wallet Card 200 HKD", price: 2550, region: "Гонконг" },
                { id: 372, name: "Steam Wallet Card 240 HKD", price: 3060, region: "Гонконг" },
                { id: 324, name: "Steam Wallet Card 300 HKD", price: 3820, region: "Гонконг" },
                { id: 373, name: "Steam Wallet Card 400 HKD", price: 5095, region: "Гонконг" },
                { id: 374, name: "Steam Wallet Card 500 HKD", price: 6370, region: "Гонконг" },
                { id: 376, name: "Steam Wallet Card HK 600 HKD", price: 7640, region: "Гонконг" },
                { id: 375, name: "Steam Wallet Card 750 HKD", price: 9550, region: "Гонконг" },
                { id: 396, name: "Steam Wallet 5 Euro", price: 650, region: "Европа" },
                { id: 392, name: "Steam Wallet 10 Euro", price: 1125, region: "Европа" },
                { id: 394, name: "Steam Wallet 20 Euro", price: 2275, region: "Европа" },
                { id: 1907, name: "Steam Wallet 30 Euro", price: 3285, region: "Европа" },
                { id: 414, name: "Steam Wallet 50 Euro  ( LIMITED PROMO )", price: 5550, region: "Европа" },
                { id: 397, name: "Steam Wallet Code 99 Rupee IN", price: 130, region: "Индия" },
                { id: 398, name: "Steam Wallet Code 150 Rupee India", price: 195, region: "Индия" },
                { id: 1908, name: "Steam Wallet Code 175 Rupee India", price: 195, region: "Индия" },
                { id: 399, name: "Steam Wallet Code 250 Rupee India", price: 325, region: "Индия" },
                { id: 400, name: "Steam Wallet Code 500 Rupee India", price: 645, region: "Индия" },
                { id: 401, name: "Steam Wallet Code 1000 Rupee India", price: 1285, region: "Индия" },
                { id: 402, name: "Steam Wallet Code 2500 Rupee India", price: 3205, region: "Индия" },
                { id: 332, name: "Steam Wallet Code Indonesia Rp 12000", price: 90, region: "Индонезия" },
                { id: 333, name: "Steam Wallet Code Indonesia Rp 45000", price: 320, region: "Индонезия" },
                { id: 334, name: "Steam Wallet Code Indonesia Rp 60000", price: 425, region: "Индонезия" },
                { id: 335, name: "Steam Wallet Code Indonesia Rp 90000", price: 635, region: "Индонезия" },
                { id: 336, name: "Steam Wallet Code Indonesia Rp 120000", price: 850, region: "Индонезия" },
                { id: 337, name: "Steam Wallet Code Indonesia Rp 250000", price: 1765, region: "Индонезия" },
                { id: 338, name: "Steam Wallet Code Indonesia Rp 400000", price: 2795, region: "Индонезия" },
                { id: 339, name: "Steam Wallet Code Indonesia Rp 600000", price: 4235, region: "Индонезия" },
                { id: 1920, name: "Steam Wallet Card 20 QAR", price: 520, region: "Катар" },
                { id: 1924, name: "Steam Wallet Card 50 QAR", price: 1300, region: "Катар" },
                { id: 1923, name: "Steam Wallet Card 100 QAR", price: 2600, region: "Катар" },
                { id: 1922, name: "Steam Wallet Card 200 QAR", price: 5195, region: "Катар" },
                { id: 1921, name: "Steam Wallet Card 400 QAR", price: 10385, region: "Катар" },
                { id: 424, name: "Steam Wallet 5000 COP - (Colombia)", price: 150, region: "Колумбия" },
                { id: 425, name: "Steam Wallet 10000 COP - (Colombia)", price: 295, region: "Колумбия" },
                { id: 426, name: "Steam Wallet 20000 COP - (Colombia)", price: 595, region: "Колумбия" },
                { id: 427, name: "Steam Wallet 50000 COP - (Colombia)", price: 1360, region: "Колумбия" },
                { id: 418, name: "Steam Wallet Code Korea 5000 WON", price: 390, region: "Корея" },
                { id: 419, name: "Steam Wallet Code Korea 10000 WON", price: 785, region: "Корея" },
                { id: 420, name: "Steam Wallet Code Korea 25000 WON", price: 1965, region: "Корея" },
                { id: 421, name: "Steam Wallet Code Korea 50000 WON", price: 3840, region: "Корея" },
                { id: 422, name: "Steam Wallet Code Korea 100000 WON", price: 7705, region: "Корея" },
                { id: 1912, name: "Steam Wallet Card 5 KW", price: 1535, region: "Кувейт" },
                { id: 1913, name: "Steam Wallet Card 10 KW", price: 3090, region: "Кувейт" },
                { id: 1909, name: "Steam Wallet Card 15 KW", price: 4630, region: "Кувейт" },
                { id: 1910, name: "Steam Wallet Card 20 KW", price: 6155, region: "Кувейт" },
                { id: 1911, name: "Steam Wallet Card 30 KW", price: 9185, region: "Кувейт" },
                { id: 403, name: "Steam Wallet Code Malaysia RM 5", price: 125, region: "Малайзия" },
                { id: 1917, name: "Steam Wallet Code Malaysia RM 8", price: 195, region: "Малайзия" },
                { id: 404, name: "Steam Wallet Code Malaysia RM 10", price: 240, region: "Малайзия" },
                { id: 1914, name: "Steam Wallet Code Malaysia RM 16", price: 385, region: "Малайзия" },
                { id: 405, name: "Steam Wallet Code Malaysia RM 20", price: 465, region: "Малайзия" },
                { id: 1915, name: "Steam Wallet Code Malaysia RM 24", price: 585, region: "Малайзия" },
                { id: 1916, name: "Steam Wallet Code Malaysia RM 48", price: 1145, region: "Малайзия" },
                { id: 406, name: "Steam Wallet Code Malaysia RM 50", price: 1195, region: "Малайзия" },
                { id: 407, name: "Steam Wallet Code Malaysia RM 80", price: 1905, region: "Малайзия" },
                { id: 408, name: "Steam Wallet Code Malaysia RM 100", price: 2315, region: "Малайзия" },
                { id: 409, name: "Steam Wallet Code Malaysia RM 200", price: 4760, region: "Малайзия" },
                { id: 428, name: "Steam Wallet 100 MXN - (Mexico)", price: 620, region: "Мексика" },
                { id: 429, name: "Steam Wallet 200 MXN - (Mexico)", price: 1235, region: "Мексика" },
                { id: 430, name: "Steam Wallet 350 MXN - Mexico", price: 2215, region: "Мексика" },
                { id: 431, name: "Steam Wallet 500 MXN - (Mexico)", price: 3085, region: "Мексика" },
                { id: 432, name: "Steam Wallet 600 MXN - Mexico", price: 3795, region: "Мексика" },
                { id: 329, name: "Steam Wallet Code 20 AED (UAE)", price: 550, region: "ОАЭ" },
                { id: 330, name: "Steam Wallet Code 40 AED (UAE)", price: 1090, region: "ОАЭ" },
                { id: 326, name: "Steam Wallet Code 50 AED (UAE)", price: 1355, region: "ОАЭ" },
                { id: 331, name: "Steam Wallet Code 75 AED (UAE)", price: 2040, region: "ОАЭ" },
                { id: 327, name: "Steam Wallet Code 100 AED (UAE)", price: 2715, region: "ОАЭ" },
                { id: 328, name: "Steam Wallet Code 200 AED (UAE)", price: 5430, region: "ОАЭ" },
                { id: 1906, name: "Steam Wallet Code 400 AED (UAE)", price: 10245, region: "ОАЭ" },
                { id: 440, name: "Steam Wallet 10 PEN - (Peru)", price: 295, region: "Перу" },
                { id: 443, name: "Steam Wallet 20 PEN - (Peru)", price: 585, region: "Перу" },
                { id: 446, name: "Steam Wallet 30 PEN - (Peru)", price: 875, region: "Перу" },
                { id: 447, name: "Steam Wallet 50 PEN - (Peru)", price: 1460, region: "Перу" },
                { id: 448, name: "Steam Wallet 100 PEN - (Peru)", price: 2915, region: "Перу" },
                { id: 351, name: "Steam Wallet 25 PLN - (Poland)", price: 705, region: "Польша" },
                { id: 350, name: "Steam Wallet 40 PLN - (Poland)", price: 1130, region: "Польша" },
                { id: 352, name: "Steam Wallet 70 PLN - (Poland)", price: 1970, region: "Польша" },
                { id: 1919, name: "Steam Wallet 110 PLN - (Poland)", price: 3100, region: "Польша" },
                { id: 108, name: "Steam Wallet Card USA 5 USD", price: 540, region: "США" },
                { id: 83, name: "Steam Wallet Card USA 10 USD", price: 1015, region: "США" },
                { id: 84, name: "Steam Wallet Card USA 20 USD", price: 2130, region: "США" },
                { id: 176, name: "Steam Wallet Card USA 25 USD", price: 2465, region: "США" },
                { id: 152, name: "Steam Wallet Card USA 50 USD", price: 4975, region: "США" },
                { id: 153, name: "Steam Wallet Card USA 75 USD", price: 7460, region: "США" },
                { id: 151, name: "Steam Wallet Card USA 100 USD", price: 9945, region: "США" },
                { id: 360, name: "Steam Wallet Code Singapore 5 SGD", price: 380, region: "Сингапур" },
                { id: 361, name: "Steam Wallet Code Singapore 10 SGD", price: 750, region: "Сингапур" },
                { id: 362, name: "Steam Wallet Code Singapore 20 SGD", price: 1500, region: "Сингапур" },
                { id: 363, name: "Steam Wallet Code Singapore 30 SGD", price: 2275, region: "Сингапур" },
                { id: 359, name: "Steam Wallet Code Singapore 50 SGD", price: 3750, region: "Сингапур" },
                { id: 1925, name: "Steam Wallet Code Singapore 75 SGD", price: 5595, region: "Сингапур" },
                { id: 377, name: "Steam Wallet Code Thailand 50 Baht", price: 155, region: "Таиланд" },
                { id: 378, name: "Steam Wallet Code 100 Baht TH", price: 305, region: "Таиланд" },
                { id: 1930, name: "Steam Wallet Code Thailand 75 Baht", price: 335, region: "Таиланд" },
                { id: 379, name: "Steam Wallet Code Thailand 200 Baht", price: 605, region: "Таиланд" },
                { id: 1929, name: "Steam Wallet Code Thailand 250 Baht", price: 770, region: "Таиланд" },
                { id: 381, name: "Steam Wallet Code Thailand 350 Baht", price: 1065, region: "Таиланд" },
                { id: 1928, name: "Steam Wallet Code Thailand 750 Baht", price: 2320, region: "Таиланд" },
                { id: 382, name: "Steam Wallet Code Thailand 1000 Baht", price: 3020, region: "Таиланд" },
                { id: 1927, name: "Steam Wallet Code Thailand 1500 Baht", price: 4475, region: "Таиланд" },
                { id: 383, name: "Steam Wallet Code Thailand 2000 Baht", price: 6015, region: "Таиланд" },
                { id: 1926, name: "Steam Wallet Code Thailand 3000 Baht", price: 9030, region: "Таиланд" },
                { id: 340, name: "Steam Wallet Taiwan 100 TWD", price: 325, region: "Тайвань" },
                { id: 341, name: "Steam Wallet Taiwan 150 TWD", price: 475, region: "Тайвань" },
                { id: 342, name: "Steam Wallet Taiwan 200 TWD", price: 630, region: "Тайвань" },
                { id: 347, name: "Steam Wallet Taiwan 300 TWD", price: 950, region: "Тайвань" },
                { id: 1932, name: "Steam Wallet Taiwan 350 TWD", price: 1095, region: "Тайвань" },
                { id: 348, name: "Steam Wallet Taiwan 400 TWD", price: 1360, region: "Тайвань" },
                { id: 343, name: "Steam Wallet Taiwan 500 TWD", price: 1575, region: "Тайвань" },
                { id: 344, name: "Steam Wallet Taiwan 800 TWD", price: 2590, region: "Тайвань" },
                { id: 345, name: "Steam Wallet Taiwan 1000 TWD", price: 3100, region: "Тайвань" },
                { id: 346, name: "Steam Wallet Taiwan 1500 TWD", price: 4970, region: "Тайвань" },
                { id: 349, name: "Steam Wallet Taiwan 2000 TWD", price: 6895, region: "Тайвань" },
                { id: 727, name: "Steam Cuzdan Kodu - 5usd (Turkey)", price: 540, region: "Турция" },
                { id: 728, name: "Steam Cuzdan Kodu - 10usd (Turkey)", price: 1070, region: "Турция" },
                { id: 729, name: "Steam Cuzdan Kodu - 20usd (Turkey)", price: 2130, region: "Турция" },
                { id: 730, name: "Steam Cuzdan Kodu - 25usd (Turkey)", price: 2540, region: "Турция" },
                { id: 1931, name: "Steam Cuzdan Kodu - 30usd (Turkey)", price: 2985, region: "Турция" },
                { id: 731, name: "Steam Cuzdan Kodu - 50usd (Turkey)", price: 5465, region: "Турция" },
                { id: 732, name: "Steam Cuzdan Kodu - 75usd (Turkey)", price: 7285, region: "Турция" },
                { id: 733, name: "Steam Cuzdan Kodu - 100usd (Turkey)", price: 9650, region: "Турция" },
                { id: 388, name: "Steam Wallet Code 50 Peso PH", price: 95, region: "Филиппины" },
                { id: 389, name: "Steam Wallet Code 100 Peso PH", price: 190, region: "Филиппины" },
                { id: 380, name: "Steam Wallet Code 250 Peso PH", price: 470, region: "Филиппины" },
                { id: 384, name: "Steam Wallet Code 500 Peso PH", price: 935, region: "Филиппины" },
                { id: 1918, name: "Steam Wallet Code 800 Peso PH", price: 1325, region: "Филиппины" },
                { id: 386, name: "Steam Wallet Code 1000 Peso PH", price: 1760, region: "Филиппины" },
                { id: 390, name: "Steam Wallet Code 2200 Peso PH", price: 4080, region: "Филиппины" },
                { id: 423, name: "Steam Wallet 5.000 CLP - (Chile)", price: 620, region: "Чили" },
                { id: 433, name: "Steam Wallet 10.000 CLP - (Chile)", price: 1235, region: "Чили" },
                { id: 435, name: "Steam Wallet 20.000 CLP - (Chile)", price: 2470, region: "Чили" },
                { id: 436, name: "Steam Wallet 100.000 CLP - (Chile)", price: 13495, region: "Чили" },
                { id: 437, name: "Steam Wallet 80 ZAR - (South Africa)", price: 465, region: "ЮАР" },
                { id: 434, name: "Steam Wallet 70 ZAR - (South Africa)", price: 485, region: "ЮАР" },
                { id: 353, name: "Steam Wallet Code 20 SAR (SA)", price: 540, region: "ЮАР" },
                { id: 438, name: "Steam Wallet 150 ZAR - (South Africa)", price: 1045, region: "ЮАР" },
                { id: 358, name: "Steam Wallet Code 40 SAR (SA)", price: 1090, region: "ЮАР" },
                { id: 354, name: "Steam Wallet Code 50 SAR (SA)", price: 1350, region: "ЮАР" },
                { id: 442, name: "Steam Wallet 250 ZAR - (South Africa)", price: 1730, region: "ЮАР" },
                { id: 441, name: "Steam Wallet 220 ZAR - (South Africa)", price: 1830, region: "ЮАР" },
                { id: 355, name: "Steam Wallet Code 100 SAR (SA)", price: 2700, region: "ЮАР" },
                { id: 444, name: "Steam Wallet 500 ZAR - (South Africa)", price: 3465, region: "ЮАР" },
                { id: 356, name: "Steam Wallet Code 200 SAR (SA)", price: 5455, region: "ЮАР" },
                { id: 439, name: "Steam Wallet 160 ZAR - (South Africa)", price: 5960, region: "ЮАР" },
                { id: 445, name: "Steam Wallet 800 ZAR - (South Africa)", price: 6655, region: "ЮАР" },
                { id: 357, name: "Steam Wallet Code 400 SAR (SA)", price: 10790, region: "ЮАР" }
            ]}
            prefix="Steam"
            isService
            />
        </Main>
    </>
    )
}