import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from 'next/font/local';
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin", "cyrillic"],
});

const boundedRegular = localFont({
  src: "../public/fonts/Bounded-Regular.ttf",
  variable: "--bounded-regular",
  display: "swap"
});

const ManropeSemibold = localFont({
  src: "../public/fonts/Manrope-Semibold.woff2",
  variable: "--monrope-semibold",
  display: "swap"
});

const ManropeRegular = localFont({
  src: "../public/fonts/Manrope-Regular.woff2",
  variable: "--monrope-regular",
  display: "swap"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${boundedRegular.variable} ${ManropeSemibold.variable} ${ManropeRegular.variable} antialiased`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
